### ISSUE TITLE
strip-ansi import error

### ISSUE THREAD

**Issue by Superpat** [cowwoc/requirements.js#35]
When I `import { requireThat } from "@cowwoc/requirements";` and try to run the code, I get the following error:

```
Error: Cannot find package 'strip-ansi' imported from .../node_modules/.pnpm/@cowwoc+requirements@4.0.7/node_modules/@cowwoc/requirements/node/internal/message/diff/DiffGenerator.mjs
Did you mean to import "strip-ansi/index.js"?
```

**Comment by cowwoc** [comment]
Hi Patrick, I'll take a look at this today. Out of curiosity, did older versions work fine?

**Comment by Superpat** [comment]
Sorry, I was out at a conference so could not respond. But I can confirm that the new release worked for me, thank you !
